name: DynamicMarketplace
version: ${project.version}
main: org.dynamicmarketplace.dynamicmarketplace.DynamicMarketplace
api-version: 1.16
depend: [Vault]
commands:
  buy:
    description: buy an item from the shop
    usage: /buy <item> <amount>
  sell:
    description: sell and item to the shop
    usage: /sell <item|hand> <amount>
  sellall:
    description: sells everything in your inventory
    usage: /sellAll
  cost:
    description: see the cost of buying an item
    usage: /cost <item> <amount>
  iteminfo:
    description: see market info on a specific item
    usage: /itemInfo <item|hand>
  worth:
    description: see the value of an item
    usage: /worth <item|hand> <amount>
  shop:
    description: The GUI Shop to buy items from
    usage: /shop
