# Applies the enchantment glint on the section items
sectionGlint: true
# Applies the enchantment glint on content items
contentGlint: false
# Applies the enchantment glint on the background panes
backgroundGlint: true
# Maps the section names to the icons they should have when doing /shop
# The names might needs to be escaped by quotation marks if they contain whitespace characters
# This is also where the sections are defined.
icons:
  "Ores and stones": STONE
  Farming: WOODEN_HOE
  "Mob drops": SPIDER_EYE
# Maps the contents of each section
# Use the names of the section as defined in the icons list
contents:
  "Ores and stones":
    - STONE
    - COBBLESTONE
    - ANDESITE
    - GRANITE
    - DIORITE
    - NETHERRACK
    - OBSIDIAN
    - COAL_ORE
    - IRON_ORE
    - GOLD_ORE
    - DIAMOND_ORE
    - EMERALD_ORE
    - NETHER_QUARTZ_ORE
    - COAL
    - IRON_INGOT
    - GOLD_INGOT
    - DIAMOND
    - EMERALD
  Farming:
    - DIRT
    - GRASS_BLOCK
    - SAND
    - RED_SAND
    - APPLE
    - BREAD
    - CARROT
    - POTATO
    - WHEAT_SEEDS
    - BAMBOO
    - BEETROOT
    - BEETROOT_SEEDS
    - CACTUS
  "Mob drops":
    - SPIDER_EYE
    - COOKED_BEEF
    - COOKED_COD
    - COOKED_PORKCHOP
    - BEEF
    - CHICKEN
    - COD
    - SALMON
    - LEATHER
    - WHITE_WOOL
    - STRING
    - ROTTEN_FLESH
    - RABBIT_FOOT
    - RABBIT_HIDE
